"""change columns type

Revision ID: c698e0297f2a
Revises: 61a31e51f9c0
Create Date: 2024-03-31 17:53:18.916715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c698e0297f2a'
down_revision: Union[str, None] = '61a31e51f9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=True),
    sa.Column('phrase', sa.LargeBinary(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret')
    # ### end Alembic commands ###
